# Generated by Django 3.1 on 2020-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(default='', max_length=50)),
                ('client_email', models.EmailField(default='', max_length=50)),
                ('client_password1', models.CharField(max_length=50)),
                ('client_password2', models.CharField(max_length=50)),
            ],
        ),
    ]
