# Generated by Django 3.1 on 2020-09-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200911_2329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
