# Generated by Django 3.1 on 2020-09-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200912_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
