# Generated by Django 3.1 on 2020-09-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200912_1857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
